services:
  ssl-cert-web:
    build: .
    container_name: ssl-cert-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # volumes:
      # 可选：如果需要持久化临时文件，可以挂载卷
      # - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ssl-cert-network
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

networks:
  ssl-cert-network:
    driver: bridge

# 可选：如果需要数据持久化
# volumes:
#   ssl-cert-data:
#     driver: local